---
title: "Assignment_1"
author: "Gustav Helms"
date: "2/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Setup
library(pacman)
pacman::p_load("tidyverse")

#Loading the data
df <- read.csv("sleepstudy.csv", header = T)
```

```{r}
ggplot(df, aes(df$Days, df$Reaction))+
  stat_summary()

hist(df$Reaction)
```

```{r}
ggplot(df, aes(Days,Reaction))+
  stat_summary(fun.y = "mean", geom = "point")+
  geom_smooth(method = "lm", fill= "lightblue",alpha = 0.5, size = 0.4)



```


Making a subset for one participant
```{r}
df$Subject <- as.factor(df$Subject)
length(levels(df$Subject))

df %>% group_by(Subject) %>% summarise(length(Subject))

participan1 <- subset(df, df$Subject == 308)

model1 <- lm(participan1$Reaction~participan1$Days)


```
###F-statistics
```{r}
#The F statistics for the effect of days on reaction time
model<-lm(participan1$Reaction~participan1$Days)
res=anova(model)
res
#Checking p-value using probability function pf()
pval<-1-pf(res$`F value`[1],1,8)
'p-value:'
pval
#Getting the F-score for the 95% significance cutoff using the quantile function qf()
cutoff<-qf(0.95,1,8)
'p=0.05 cutoff value with df(1,8)'
cutoff
```
####Making a F-distribution plot with the cutoff and the resulting F-value
```{r}
#Making a string of 100 numbers beteen 0 and 20 to use when finding the F distribution
nn<-seq(0,20,len=100)
#Getting the F distribution using df()
fdist<-df(nn,1,8)
plot(nn,fdist, type='l',xlab='F value - df(2,12)',ylab='Density')
#plotting a vertical line at the cutoff
lines(c(cutoff,cutoff),c(0,1),col='darkgreen')
#Add explanation for the line
text(cutoff+2,0.5,'p=0.05',col='darkgreen')
#draw F-value as point on the curve
points(res$`F value`[1],df(res$`F value`[1],2,12),col='red')
#add text for the f-value
text(res$`F value`[1]+2,0.1,'f=17,118',col='darkgreen')



```


```{r}
fdist<-df(participan1$Reaction,1,8)
plot(participan1$Reaction,fdist, type='l',xlab='F value - df(1,8)',ylab='Density')
```

